name: py311_dgm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tqdm
  - gdown
  # Data Analysis
  - scipy
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - pillow
  - opencv
  # Plotting
  - matplotlib
  - seaborn
  # Machine learning
  - scikit-learn
  - catboost
  # Deep Learning
  - pyro-ppl 
  - pytorch-lightning
  - tensorboard
  # Jupyter Environment
  - ipykernel
  - jupyterlab
  - jupyter
  - ipywidgets
  - pip:
    - comet-ml
