name: py311_dgm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tqdm
  - gdown
  # Data Analysis
  - scipy
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - pillow
  - opencv
  # Plotting
  - matplotlib
  - seaborn
  # Machine learning
  - scikit-learn
  # Deep Learning
  - pytorch::pytorch
  - torchvision 
  - torchaudio
  # Jupyter Environment
  - ipykernel
  - jupyterlab
  - jupyter
  - ipywidgets
  - nb_conda_kernels
